### ISSUE TITLE
Feature additions for the AutoStationConfig Mod

### ISSUE THREAD

**Issue by Korrakore** [Pasukaru/DSP-Mods#11]
Hey there, I would like to recommend a couple of feature additions to the AutoStationConfig mod, namely an ability to change the warper storage from 100 default to max 10000, like an option in the config file for it, and an option to dedicate a 6'th slot to the ILS, specifically for this, already we have only 5 slots, and the biggest recipe takes 6 on it's own, so it would be better if you could dedicate a slot for this without interfering with the existing 5, or even better if you could configure the ILS to have total 7 slots and have 1 dedicated to warpers, in this way the biggest recipe can be crafted using the same ILS and we could also request warpers. Let me know your opinion for these features.

**Comment by Pasukaru** [comment]
Thanks for your feedback!
Using dedicated slots is something I thought about, however, I don't want this mod to break save games.
Adding additional slots to stations would do that, and it would also interfere with other mods that already do that.

Having a configurable warper storage is possible, but I don't see the benefit. IMHO, 100 is plenty - that leaves you with 254 in storage. 50 in the dedicated warper storage, 99 will trigger the next drone bringing in an additional 100. That's enough buffer for 12 trips for each vessel.

**Comment by Korrakore** [comment]
Well that's true, but tbh if you just have a option in the config file that gives you an option to enable 6'th slot, in that case it would not break save games, also 100 is plenty, accepted, but it feels like a waste that you could theoretically have like 10000 warpers but you still cheap out and store 100, nothing sensible, but feels like a waste, anyways it's on you to develop this further or not, but having the options would be better, like for example a phone that does video calling is good, doesn't necessarily mean that if you don't use it you don't need it, sometimes, in rare cases they benefit a lot tbh, that's why I made the recommendation. Still, think about it. Have a good day/night.

**Comment by Pasukaru** [comment]
Closed via #15
