### ISSUE TITLE
crash on placing ILS

### ISSUE THREAD

**Issue by Byste** [Pasukaru/DSP-Mods#21]
![Screenshot 2024-02-03 104951](https://github.com/Pasukaru/DSP-Mods/assets/37183152/fd4bc3ab-78f3-4365-9cb8-1c5f8cb68960)

Placed my first ILS, immediately corrupted my save file. Mod version 1.4.0, game version 0.10.29.21904

**Comment by Pasukaru** [comment]
The mod is way out of date. It was made before blueprints and the vanilla autofill option existed.
I'm not going to update it, not much reason now that the 2 features exist in vanilla.

There is, however, a fix from starfish that may or may not work (I've never tested it):
https://dsp.thunderstore.io/package/starfi5h/ModFixerOne/

**Comment by Byste** [comment]
Sorry to bother you! Your mod came highly recommended in the mod store
despite all the time that's passed 😊 Perhaps it can get designated as
defunct or removed so people like me stop downloading it mistakenly?
