### ISSUE TITLE
Seems like config option "Vessel insert percentage" doesn't work; instead the "Drone insert percentage" is used for vessels

### ISSUE THREAD

**Issue by Veretragna** [Pasukaru/DSP-Mods#4]
Pretty much this. 
If I set "Drone insert percentage" to 0.4 and "Vessel insert percentage" to 1, ILS is created with 20 drones and 4 vessels, while there should be 10 vessels. Please check.
![2021-03-03_221433](https://user-images.githubusercontent.com/14805612/109866428-f0503580-7c6d-11eb-8ecd-3fd0a04a1aa4.jpg)

**Comment by Pasukaru** [comment]
On it :)

**Comment by Pasukaru** [comment]
Fixed in 1.2.1: https://github.com/Pasukaru/DSP-Mods/tree/AutoStationConfig-v1.2.1

**Comment by Veretragna** [comment]
Thanks! Now it's working
